### ISSUE TITLE
Author meta

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/byline-manager#14]
Profiles ideally will be able to be interacted with the same as a post author would.

* [ ] Filter `get_the_author_{$field}` for all relevant fields
* [ ] Consider fabricating the global `$authordata` object
* [ ] Consider overriding the pluggable `get_userdata()`
